apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeguard.fullname" . }}
  labels:
    {{- include "kubeguard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubeguard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubeguard.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kubeguard.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.aws.secretName | default "kubeguard-aws-creds" }}
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.aws.secretName | default "kubeguard-aws-creds" }}
                  key: secret_access_key
            - name: SLACK_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.alerts.secretName | default "kubeguard-alerts" }}
                  key: slack_webhook
            - name: SNS_TOPIC_ARN
              value: {{ .Values.alerts.snsTopicArn | quote }}
            - name: AWS_REGION
              value: {{ .Values.audit.awsRegion | quote }}
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: {{ include "kubeguard.fullname" . }}-config
